name: Codecov

  #on:
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]


jobs:
  coverage:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3

    - name: Install LCov
      run: sudo apt-get update -q
        && sudo apt-get install lcov -q -y

    - name: Configure
      run: cmake --preset=ci-coverage

    - name: Build
      run: cmake --build build/coverage -j 2

    - name: Test
      working-directory: build/coverage
      run: ctest --output-on-failure -j 2

    - name: Process coverage info
      run: cmake --build build/coverage -t coverage

    - name: Submit to codecov.io
      uses: codecov/codecov-action@v3
      with:
        file: build/coverage/coverage.info
